Repository steevejoseph/contact-manager, pull requests merged in 2018-09, with the labels that each got.

#56 Dashboard draft
  public/scripts/plsdel.html
  public/scripts/splash.js
  public/stylesheets/dashboard.css
  public/stylesheets/style.css
  views/dashboard.ejs
  views/splash.ejs
Labels: frontend

#60 Sign out branch
  index.js
  seeds.js
  views/dashboard.ejs
Labels: auth, backend, frontend

#59 initial work on seeds
  seeds.js
Labels: development
